REWORK CHANNEL (BACKEND):
42rave/transcendence pull request #36
Opened 2023-09-19 22:31 UTC by riblanc

Refactoring the join channel method to simplify the logic, performing fewer database accesses.
This new logic will subsequently allow us to be able to join a socket.io room specifying a socket.id, more easily.

2023-09-19 22:45 UTC, riblanc commented
I'd like to review this PR with you @AdrianWeaver as I changed most of the join channel method.
I still apply the same logic as you did, but making fewer database calls, less if statements and removing redundant code.

See you at school!

2023-09-20 12:42 UTC, AdrianWeaver requested changes

2023-09-20 12:42 UTC, AdrianWeaver commented on back/src/chat/channel/channel.service.ts
> +    return !!(await this.getChannelConnection(userId, channelId));
Something like that maybe?
```suggestion
    const channelConnection = await this.getChannelConection(userId, channelId));
    if (!channelConnection || channelConnection.role === channelRole.INVITED
      || channelConnection.role ==== channelRole.BANNED)
      return false
    return true;
```

2023-09-20 12:51 UTC, AdrianWeaver commented on back/src/chat/channel/channel.service.ts
> +    return !!(await this.getChannelConnection(userId, channelId));
updated in : [4da690d](https://github.com/42rave/transcendence/pull/36/commits/4da690d473b70ada9865cb0e1fdf933ac74956ca)

2023-09-20 13:10 UTC, AdrianWeaver commented
Let's all pretend you did not see me push --force on this branch :innocent:

2023-09-20 13:10 UTC, merged