MERGE PRODUCTION ENVIRONMENT:
42rave/transcendence pull request #57
Opened 2023-10-01 16:17 UTC by riblanc

**Description:**
This pull request introduces the necessary changes to add a production environment configuration to the project.
It includes updates to configuration files and Docker setups to ensure a seamless transition to production mode.

**Changes Made:**

1. **.env.sample**:
   - Added production-specific environment variables.
   - Updated API_URL and WS_BASE_URL to match production URLs.

2. **.gitignore**:
   - Added .env.dev to the gitignore file.

3. **back/Dockerfile**:
   - Added a new Docker build stage for production.
   - Copies the necessary production files and dependencies.
   - Sets NODE_ENV to production for the production image.

4. **back/entrypoint.sh**:
   - Updated to export NODE_ENV as production.

5. **front/Dockerfile**:
   - Added a new Docker build stage for production.
   - Copies the production build output.

6. **front/entrypoint.sh**:
   - Updated to export NODE_ENV as production.

7. **front/nuxt.config.ts**:
   - Updated the default API_URL and WS_BASE_URL for production.

8. **front/stores/auth.store.ts**:
   - Updated API_URL references to use the production URL.

9. **docker-compose.dev.yml**:
   - Added a development-specific Docker Compose file.

10. **docker-compose.yml**:
    - Updated Docker Compose file for production.
    - Added NGINX configuration for reverse proxying to the frontend and backend.

11. **proxy/templates/default.conf.template**:
    - Added NGINX configuration for reverse proxying to the frontend, backend, and WebSocket.

12. **proxy/entrypoint-wrapper.sh**:
    - Added a script to control NGINX start based on NODE_ENV.

**How to Test:**
1. Clone this branch and navigate to the project directory.
2. Run `docker-compose up --build` for production or `docker-compose -f docker-compose.yml -f docker-compose.dev.yml up --build` for development.
3. Verify that the project runs without errors in both development and production environment.

Close #49

2023-10-02 09:57 UTC, AdrianWeaver commented
I don't have the time to feedback this right now I'm sorry...
But I thought I heard you talk about changing the Makefile as well and I don't see any changes to it?

2023-10-02 12:45 UTC, Elena-Lou requested changes
Thank you for your work on this. The difference between "prod" and "dev" environment has always been very abstract to me but thanks to this, it is becoming clearer

2023-10-02 12:45 UTC, Elena-Lou commented on back/Dockerfile
> +ARG WEB_APP_URL="http://localhost"
```suggestion

```

2023-10-02 12:45 UTC, Elena-Lou commented on back/Dockerfile
> +ARG WEB_APP_URL="http://localhost"
We agreed during review that they were useless in the dockerfile

2023-10-02 12:45 UTC, Elena-Lou commented on docker-compose.yml
> +      - ./back/.env
```suggestion
```
The Database url being already in the environment from the dotenv, there is no need for the backend one

2023-10-02 12:45 UTC, Elena-Lou commented on front/layouts/default.vue
> +    console.log('beforeMount: ', this.$config.app.API_URL);
```suggestion

```
Lonely debug

2023-10-03 13:12 UTC, Elena-Lou approved these changes
Thank you for the updates and improvment

2023-10-03 13:12 UTC, merged